#!/usr/bin/env python

import logging
import re
import sys


logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger(__name__)

def load(path):
    with open(path, 'rb') as f:
        return [line.strip() for line in f.readlines()]

images = load('images.txt')
backgrounds = load('backgrounds.txt')

def replace_id(match):
    attr = match.group(1).lower()
    group = match.group(2)
    quote_char = group[0]
    asset_id = int(group[1:-1])

    if attr == 'bg':
        new_id = asset_id % len(backgrounds)
    else:
        new_id = asset_id % len(images)

    log.debug("{}: {} -> {}".format(attr, asset_id, new_id))

    return '{}={}{}{}'.format(attr, quote_char, new_id, quote_char)

html = re.sub(
    r'\b(src|bg)\s*=\s*("\d+"|\'\d+\')',
    replace_id,
    sys.stdin.read(),
    flags=re.IGNORECASE,
)

print(html)
