#!/bin/bash

set -e

script_name="$0"
verbose=0
fixup_embeds=0
force=0
posargs=()

fixup_embeds_if_required() {
  if [[ "$fixup_embeds" -eq 1 ]]; then
    cmd="scripts/fixup-embeds"

    if [[ "$verbose" -ge 2 ]]; then
      cmd="$cmd --verbose"
    fi

    $cmd
  else
    cat
  fi
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    "-v"|"--verbose")
      verbose=$((verbose + 1));;
    "--fixup-embeds")
      fixup_embeds=1;;
    "--force")
      force=1;;
    *)
      posargs+=("$1");;
  esac

  shift
done

if [[ "${#posargs[@]}" -ne 2 ]]; then
  >&2 echo "Usage: $script_name [-v|--verbose] [-p|--preserve-filenames] SOURCE_DIR TARGET_DIR"
  exit 1
fi

source_dir="${posargs[0]}"
target_dir="${posargs[1]}"

for path in $source_dir/*.html; do
  destination="${target_dir}/$(basename $path)"

  if [[ -f "$destination" && "$force" -ne 1 ]]; then
    if [[ "$verbose" -ge 1 ]]; then
      >&2 echo "Skipping $destination - already exists"
    fi
    continue
  fi

  if [[ "$verbose" -ge 1 ]]; then
    >&2 echo "Generating $destination"
  fi

  cat "$path" \
    | sed -e $'s/\x1B\[0m//' \
    | scripts/ids-to-urls \
    | scripts/remove-swallowing-tags \
    | fixup_embeds_if_required \
    > "$destination"
done
